# Generated by Django 4.0.5 on 2022-06-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('accountid', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(db_column='email', max_length=40)),
                ('pw', models.CharField(db_column='pw', max_length=40)),
                ('pwcheck', models.CharField(db_column='pwcheck', max_length=40)),
                ('name', models.CharField(db_column='name', max_length=10)),
                ('birth', models.DateField(db_column='birth')),
                ('gender', models.IntegerField(choices=[(1, '남성'), (2, '여성')], db_column='gender')),
            ],
            options={
                'db_table': 'account',
                'managed': False,
            },
        ),
    ]
